[package]
name = "dolos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
logos = "0.13.0"
peg = "0.8.1"
pest = "2.7.1"
pest_derive = "2.7.1"
pretty_env_logger = "0.5.0"
